### ISSUE TITLE
[Spike] Investigate how to use EC with x509

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-diag#169]
Investigate how we can:

* Generate a CSR on the EC
* Sign and store the certificate
* Upload it to Google Core IoT for consumption in MQTT

**Comment by shawaj** [comment]
Pretty sure we can do units already with the way our ECC key is set up. Worst case scenario we may need to generate some new keys in a few keyslots but I don't think we actually need to do that.

Will perform some tests later this week

**Comment by vpetersson** [comment]
I have received the EC developer kit now so we can start doing some testing on this.

**Comment by vpetersson** [comment]
From Microchip:

The latest versions of all of those demos are now built into in the Trust Platform Design Suite I referred to below – there’s a MPLabX project in there (which is now called “cloud connect” as it support Azure, AWS and Google all in one) that you could download to our dev board and then using one of our WINC1500 modules would allow you to could connect it to Google.
 
If you don’t want to downloaded and install the whole TPDS tool chain (from here: https://www.microchip.com/en-us/product/SW-TPDSV2 )  just to get the cloud connect project firmware project then I could extract the MPLabX project for you and just zip it up and send it.
 
Other option would be to grab the version that was released in TPDSv1 direct from Github here: (https://github.com/MicrochipTech/cryptoauth_trustplatform_designsuite/tree/master/TrustFLEX/10_cloud_connect/firmware)
 
However, if you’re actually running Linux, then most people go down the PKCS11 route so you may want to look at this instead:  https://github.com/MicrochipTech/cryptoauthlib/wiki/PKCS11-Linux-Setup  as it explains how you can compile cryptoauthlib as a PKCS11 driver to plug into your Linux subsystem.

**Comment by MuratUrsavas** [comment]
I've experimented a lot what's required and came to a conclusion.

We can do it, but we shouldn't be using pkcs11 tool. Instead we'll go with Python wrapper of CryptoAuthLib. So that we will be able to unlock all features of ECC (including locking the slots we use). 

What we'll follow:

* A part of this setup (building and installing the CryptoAuthLib)
* Applying workaround written in [this](https://github.com/MicrochipTech/cryptoauthlib/issues/203) page while doing the above task.
* Will use the [python wrapper of CryptoAuthLib](https://pypi.org/project/cryptoauthlib/)
* And we'll take the [examples](https://github.com/MicrochipTech/cryptoauthtools/tree/master/python/examples) as starting point of our implementation.

Caveat:
The python wrapper supports ATECC608A, not B. So there might be a small friction while implementing the solution. But the CryptoAuthLib is supporting the B version. It should be trivial to add support for ATECC608B.

In case the implementation would require a lot of effort than anticipated, than the pkcs11 tool will be there for us for help with a small loss of features we want.

Since this issue was just a spike, I'm now closing it and create an implementation issue next.
