### ISSUE TITLE
Track basic hotspot uptime and load

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#218]
Possibilities:

- Hotspots report their uptime/load with each payload
- Look at average number of payloads over some period
- Sample subset of hotspots

Use Google Data Studio for displaying results.

**Comment by marvinmarnold** [comment]
The dashboard on Data Studio should be able to answer questions like:
- What's the average uptime of all our hotspots. What's the longest a hotspot has been up for?
- What percentage of all our hotspots are synced
- What percentage of all hotspots are online (Balena)
- What version are hotspots that are down running?

**Comment by vpetersson** [comment]
@SebastianMaj you should have access to BigQuery now.

**Comment by SebastianMaj** [comment]
<img width="429" alt="Screen Shot 2021-11-22 at 9 23 02 PM" src="https://user-images.githubusercontent.com/6146752/142962463-7d98de4a-665f-468c-8860-a92d5ea10de0.png">
I think I still lack access, this is all I see under our org in BigQuery and when I check the project it returns nothing for the dataset and it doesn't have a table view either. @vpetersson

**Comment by vpetersson** [comment]
That's the wrong project. You should have received an invite that you need to accept.

**Comment by SebastianMaj** [comment]
@marvinmarnold @vpetersson 

I've been playing around with Google Data Studio and this is extremely powerful and it's super cool on how it interfaces with our BigQuery tables to allow us to display data in realtime with different formats that resemble a dashboard. Based on my analysis we have all the fields already present to show useful charts and diagrams that will help us visualize a lot of the information on the miners and how the fleet is operating. 

It seems like the only additional field we will need is the uptime so that we can display average uptime across the fleet and also the highest uptime on a miner. To add this field we can go one of 2 ways:

1) We can try and interface with Balena to grab this value and include it in the balena_helper table which will require us to create a migration in hm-dashboard to add this new field and then we can populate it by interfacing with the Balena API

2) We can use the diagnostics reports to upload a system uptime by using linux uptime command and supplying that value to the diagnostics report that is uploaded to google cloud services. This will require a schema change in BigQuery but should provide the same result we are looking for.

**Comment by SebastianMaj** [comment]
More fields may show up overtime if I find more useful charts that we can display in our reports

**Comment by SebastianMaj** [comment]
It would also be nice to have a line chart showing the following data over time:
- Devices synced over time
- Devices online/offline over time

This would help us visualize how devices are doing over a period of time instead of at the exact moment so we can see if any improvements occurred. After thinking about it, the best way to do this might be to make a new table in BQ and have it be a "Fleet Status" table which has the purpose of keeping track of the values over time. Then we will run a scheduled query which will fetch the count of devices that are online, offline and synced and then use that data to create a new entry in the table with a timestamp. Then we can use this data to display a line chart with a clear view of how the entire fleet is doing over time.

**Comment by SebastianMaj** [comment]
Would it be useful to include the uptime on the diagnostics page itself as well? Might be a nice addition for the customers to see this information. 

Right now I have it only under gcs_shipper in a custom branch [here](https://github.com/NebraLtd/hm-diag/blob/867796f3decba23b524c5b8d51efd615dd0fbae9/hw_diag/utilities/gcs_shipper.py#L43)

I can include this in the tasks.py process and then display it on the diagnostics page so that consumers can see this information

**Comment by marvinmarnold** [comment]
> Would it be useful to include the uptime on the diagnostics page itself as well? Might be a nice addition for the customers to see this information.

Can you create a new issue for this and we can scope it out in more detail for a future sprint? Also worth considering if we want this on diag, dashboard, or both.

**Comment by marvinmarnold** [comment]
@SebastianMaj can you share the report with @KevinWassermann94 for his feedback?

**Comment by KevinWassermann94** [comment]
@SebastianMaj Yes please!

**Comment by KevinWassermann94** [comment]
This is super helpful, great work!

There is some features I would like to see on top of it:
- time since last PoC activity (might be a bit more complex)
- storage used(less than 20%, 40%, 60%,... , full)
- earnings per day (amount of hotspots earning 0,1HNT, 0,2HNT, ... per day)
- split between sub frequencies (AS923, AU915, etc)
- miners connected to blockchain
- Lora status by sub frequency
- ECC detected
- Wifi detected

**Comment by marvinmarnold** [comment]
Thanks for the feedback Kevin. Lets focus on closing this ticket by any means today @SebastianMaj. Make sure to include Kevin's feedback in the criteria for the follow up ticket you are creating.

**Comment by SebastianMaj** [comment]
Follow up Issues created:
#262  - Uptime pushed to GCS
#258 - Display uptime on Frontend
#261 - Fleet Analytics Report Followup
