### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by justkidding96** [NebraLtd/hm-diag#227]
After almost a week of emailing about this problem, I'll give it a try. When will this issue be resolved. Due to the 500 internal server error I can no longer connect via bluetooth. Please let us known when this issue will be fixed.

**Comment by Working4u** [comment]
This happens for a lot of devices right now.

În joi, 18 nov. 2021 la 17:34, Rowdy Klijnsmit ***@***.***> a
scris:

**Comment by justkidding96** [comment]
@Working4u Thanks for your comment, still this is no answer why this happens.

**Comment by schludini** [comment]
I just plugged in my Nebra miner this morning for the first time... it booted up and the green light came on, it went from flashing to solid before I could sync it to my app... I restarted the miner and now the green light won't come back at all... I'm reading about the internal server error ... but I'm wondering if it could be a different problem because the green light initially came on and it was only after I powered off/on that it stopped appearing.... thoughts?   do people think it's still the same root cause?

**Comment by atsepkov** [comment]
Not seeing green light come on either, no witnesses and 500 error after the last network outage a couple days ago. All other miners in the area are online and earning HNT so it doesn't seem like the issue is with Helium network anymore. Prior to outage the miner worked fine.

**Comment by AirportDrunk** [comment]
Thanks for opening this issue. I have been having the same problem with my outdoor Nebra for a few days. It has worked again after rebooting but always goes back to 500 error. Last night after the firmware update 17.2  It has not worked since despite rebooting. Also I noticed that my router is showing a different IP than the assigned static for the Nebra unit. I can get the internal server error on the static and I can get a ping response from the other address as well. The rogue address also shows up on IP scan. The rogue address appeared after the 500 internal error issue last night. I saw someone on reddit mention this as well.

**Comment by badaczewski** [comment]
I have an open support ticket for this issue right now:

- No Green Light
- No Bluetooth Connectivity
- Internal Server Error for Local Diagnositics

**Comment by justkidding96** [comment]
@marvinmarnold @shawaj Can someone answer our questions about this issue? Because I see allot of activity but no answers where given..

**Comment by shawaj** [comment]
This is not a support forum.

Email support@nebra.com

**Comment by shawaj** [comment]
P.S. the issues relate to the massive helium outages that have occurred in the last week. There is nothing we can do about them unfortunately
