### ISSUE TITLE
Fleet Analytics Report Followup

### ISSUE THREAD

**Issue by SebastianMaj** [NebraLtd/hm-diag#261]
**User Story**
We want to view more information about the fleet and see specific reports on Google Data Studio. 

**Notes**
We currently have the following data displayed on our Fleet Report in Google Data Studios:

- What's the average uptime of all our hotspots. What's the longest a hotspot has been up for?
- What percentage of all our hotspots are synced
- What percentage of all hotspots are online (Balena)
- What version are hotspots that are down running?
- Firmware version across the fleet with the variation + frequency
- Number of devices online/offline/synced/unsynced over time

We want to add some more data to the report to show more information about our fleet and create some more graphs/charts to display this data.

List of potential charts we can add:
- More detailed charts that drill down deeper into the specifics of the data present
- (Add More)

**Acceptance Criteria**
- Time box to 1 point, move additional work to follow up ticket

**Comment by KevinWassermann94** [comment]
Copying my features requests from the other thread in here:

- time since last PoC activity (might be a bit more complex)
- storage used(less than 20%, 40%, 60%,... , full)
- earnings per day (amount of hotspots earning 0,1HNT, 0,2HNT, ... per day)
- split between sub frequencies (AS923, AU915, etc)
- miners connected to blockchain
- Lora status by sub frequency
- ECC detected
- Wifi detected
