### ISSUE TITLE
Disregard Colons in Password Field

### ISSUE THREAD

**Issue by Ryan-Goldstein** [NebraLtd/hm-diag#463]
Opening this issue as suggested in https://github.com/NebraLtd/helium-miner-software/pull/574#issuecomment-1398560174.

Since the default password is the device's MAC address, and MAC addresses are reported on the label, in the Nebra Dashboard, and elsewhere with colons, I propose stripping out all instances of colons in the entered password before determining whether that password is valid.

This would also allow removal of the "without any colons" wording on the login page.

For changing the password, you may want to disallow colons as a valid character, or simply strip them out before setting the password.

**Comment by shawaj** [comment]
After talking to @robputt this isn't going to work unfortunately. Because if we strip the colons from password no colons will work in any password which will be confusing.

Possibly having it as with the colons would have been better, but now the update has been pushed all miners will have the password without colons in the database, meaning changing this would only affect new units, which would then be even more confusing as we will have some without colons and some with.

Thanks very much for the suggestion though @Ryan-Goldstein - probably would have been better but unfortunately we can't do much about it now

**Comment by Ryan-Goldstein** [comment]
Thanks for the quick review and consideration. Wouldn't preventing colons from being used as a valid character in passwords resolve that issue? Or stripping out colons before saving a newly set password?
