### ISSUE TITLE
Auto register Third party devices on Dashboard

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#470]
Acceptance Criteria:
- Auto register devices on Dashboard when not in manufacturing mode
- Only attempt once on first boot
- Button in diagnostics with deeplink to claim device on the Dashboard

**Comment by shawaj** [comment]
Endpoint is https://dashboard.nebra.com/api/v0.1/register-third-party-hotspot

Example code:

```
 import requests
 import json
 
 url = "https://dashboard.nebra.com/api/v0.1/register-third-party-hotspot"
 device = {
     "ethernet_mac_address": "00:00:00:00:00:00",
     "wifi_mac_address": "00:00:00:00:00:00",
     "frequency": "915",
     "balena_uuid": "valid uuid",
     "onboarding_address": "onboarding_address",
     "public_address": "public_address",
     "serial_number": "serial_number",
     "variant": "NEBHNT-HHRK4"
 }
 
 register = requests.post(url, data = json.dumps(device), headers = {'Content-Type': 'application/json; charset=UTF-8'})
 
 print(register.text)
```

Returns:
```
{"detail":"This device is not running on Nebra software."}

Or

{"detail":"This device is not running on Nebra software."}
```

Ref...
```
HTTP 200 OK
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "name": "Register Third Party Hotspot",
    "description": "",
    "renders": [
        "application/json",
        "text/html"
    ],
    "parses": [
        "application/json",
        "application/x-www-form-urlencoded",
        "multipart/form-data"
    ]
}
```

**Comment by shawaj** [comment]
After discussion with @KevinWassermann94 in the above Slack thread, thinking the best way forward is to:
- call the API endpoint automatically (only once) on first load of the diagnostics container to make sure all devices running Nebra firmware on third party devices are logged in our system ready for hooking up to dashboard (log any errors to both dashboard and in diagnostics syslog)
- add to dashboard page, or similar (maybe just on the main info page so it is front and center?) display a deep link (perhaps with a query string appended to URL https://dashboard.nebra.com/devices/#qr-modal that pre-populates the serial and Mac address in the manual entry section of the modal) and a QR code for adding the device to the dashboard
- for the deep link mentioned in the above step, if the customer isn't logged in to the dashboard at the time it should take them to the login page and once logged in redirect them to the add device modal (I noticed that currently if you are logged out and head to the domain https://dashboard.nebra.com/devices/#qr-modal it asks you to log in but you are then redirected to https://dashboard.nebra.com/#qr-modal instead of https://dashboard.nebra.com/devices/#qr-modal which is not ideal IMO)
- perhaps we should expose an API endpoint on dashboard where a device can automatically detect if the device belongs to a paid dashboard account? (Currently we do this by detecting if it's in a fleet with name ending with -c but this isn't really ideal because this could be triggered accidentally - checking for -c ending and a specific API endpoint would be a better way IMO)
