### ISSUE TITLE
Investigate issue with manufacturing mode

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#518]
Acceptance Criteria:
- Revisit the manufacturing mode
- Option to disable manufacturing mode

**Comment by kashifpk** [comment]
@shawaj - This happens because even if the miner is not directly on the network we can still get a reply from any router down the line. As any network that is not local is forwarded to the the internet gateway which in turn forwards it to the next gateway. If any of these gateways is misconfigured or setup to allow public internet ip traffic to this private network range then we run into this issue. See screenshot below, my network doesn't have this range either but somehow down the line in or after my ISPs network packets get forwarded to it.

![image](https://user-images.githubusercontent.com/198638/230681304-a30de5ef-866b-43af-8c44-11bdb15c2dce.png)


The fix fortunately is two fold and simple. First for ip check we check the ping ttl count to ensure that the miner is directly connected to this ip and there are no machines in between. Second if the env variable is present it takes precedence over ping check. Current implementation assumes a default value for the env variable if it's not found. I'll update that so if the env variable is not present only then we do ping check.

So the proposed workflow is:

1. Check if `IN_MANUFACTURING` env variable is present, if yes set manufacturing mode to True/False based on the env var value.
2. If env var not found then ping `192.168.220.1`, if no reply received then not in manufacturing mode.
3. If reply received then check ttl < (254 or 127 - need to verify) then not in manufacturing mode, else device is in manufacturing mode.

This would cover most cases where we incorrectly detect manufacturing mode and by change if a user's local network actually uses the 192.168.220.0/24 subnet then we can just set the `IN_MANUFACTURING` env variable for that user's device to fix it.

**Comment by shawaj** [comment]
@kashifpk can we close this one now then?

**Comment by kashifpk** [comment]
@shawaj - it's in Testnet. Don't think it would break anything but better be sure about it. So once firmware with this change is on testnet for 24 hours, I'll close it.
