### ISSUE TITLE
Relayed status

### ISSUE THREAD

**Issue by bigdaveakers** [NebraLtd/hm-diag#54]
Is it possible to show the "Miner Relayed" row in amber if the value is true and also indicate this in the main status "All Ok" is not an accurate reflection of this state as beaconing will not work.

I have found that the diagnostic page is the only place that shows the real time relayed state and that the explorer, Helium App, and dashboard all indicate that there is no relayed state even after many hours/days.

It may be also worth considering adding a link if the hotspot is relayed to a page that shows how to fix it.

**Comment by ryanteck** [comment]
It might be we have to look at adding a third state in, maybe as a warning state or such.

Essentially ALL OK displays if the tests which are done for production pass. as this wouldn't be a production failure it wouldn't affect the test.

We could possibly add a warning state, so that then the bits like this are picked up maybe.

**Comment by ryanteck** [comment]
Now Partially implemented, if the device is relayed it turns it to amber. If not it now turns to green.

![Screenshot from 2021-06-09 11-49-23](https://user-images.githubusercontent.com/1104745/121341883-ff9fe880-c918-11eb-884e-d8e1b02a9cb7.png)

![Screenshot from 2021-06-09 11-49-18](https://user-images.githubusercontent.com/1104745/121341886-00387f00-c919-11eb-8274-c575d934317d.png)

**Comment by vpetersson** [comment]
This is still an issue. Not introduced in the rewrite, but an issue:
<img width="1158" alt="Screen Shot 2021-08-16 at 2 43 06 PM" src="https://user-images.githubusercontent.com/357664/129573256-153ee7a5-2b38-465d-8769-8202a70f88b7.png">

This is a screenshot from a miner that does not have an port forwarding to it so 'Miner Relayed' should definitely be True.

**Comment by ryanteck** [comment]
Was working beforehand :)

**Comment by vpetersson** [comment]
Except that it wasn't.

**Comment by ryanteck** [comment]
mhm sure it wasn't.

Could you unsubscribe me from everything please? I keep unsubscribing but
still get emails through of stuff breaking :)

**Comment by shawaj** [comment]
The problem with this is that it was written by Ryan in such a way that it only checks for `symmetric` output from the `miner info p2p_status` command

https://github.com/NebraLtd/hm-diag/blob/1444a3b2ccfcec7c6b505ede8dd2ecfa31b1e831/diagnostics-program/main.py#L144-L148

Which is a hacky way to determine the relayed status IMO.

**Comment by vpetersson** [comment]
@robputt is this something we can get from the local API?

**Comment by shawaj** [comment]
The way helium determine it is from whether the listen_addr has an ipv4 address

https://github.com/helium/explorer/blob/214bc8008eb0d532ad1e9fd8242dd71a7e3bc53f/components/Hotspots/utils.js#L133-L134

I believe we can get this from the helium API

**Comment by ryanteck** [comment]
> The problem with this is that it was written by Ryan in such a way that it only checks for `symmetric` output from the `miner info p2p_status` command
> 
> https://github.com/NebraLtd/hm-diag/blob/1444a3b2ccfcec7c6b505ede8dd2ecfa31b1e831/diagnostics-program/main.py#L144-L148
> 
> Which is a hacky way to determine the relayed status IMO.

This was actually how Helium checked for it IRC.

So Helium's implementation was hacky, I just re-did it.

**Comment by shawaj** [comment]
For example this is gigantic basil turtle and is not relayed https://api.helium.io/v1/hotspots/112mPWkGW55kcbQTgbtJvgAKMSTrEhHgavrdF1Cbu8FU85tTL4Nc

**Comment by shawaj** [comment]
Here is a relayed one https://api.helium.io/v1/hotspots/116w79GGtZCQ7FuECaGJh2m8Gbpu2utvRy7NydbBEq7xvAzbhBk

As you can see output has /p2p/ instead of /ipv4/

```
{"data":{"speculative_nonce":1,"lng":15.667515997677613,"lat":43.818426714385005,"timestamp_added":"2021-07-24T14:31:29.000000Z","status":{"timestamp":"2021-08-16T16:46:38.951000Z","online":"online","listen_addrs":["/p2p/11MavepXJUYmGQapgkmLabK9iF9iMXEvhwFWHgmrtPSGQRQKSUG/p2p-circuit/p2p/116w79GGtZCQ7FuECaGJh2m8Gbpu2utvRy7NydbBEq7xvAzbhBk"],"height":968084},"reward_scale":1.0,"payer":"13Zni1he7KY9pUmkXMhEhTwfUpL9AcEV1m2UbbvFsrU9QPTMgE3","owner":"146tDYBgeevccVKLBhrxAsYgfrzoo7eDtLGWKEZRuoJUePodFST","nonce":1,"name":"steep-fuzzy-barbel","mode":"full","location_hex":"881ea8473dfffff","location":"8c1ea8473c36dff","last_poc_challenge":968080,"last_change_block":968080,"geocode":{"short_street":"Ante Starčevića","short_state":"Šibensko-kninska županija","short_country":"HR","short_city":"Pirovac","long_street":"Ante Starčevića","long_state":"Šibensko-kninska županija","long_country":"Croatia","long_city":"Pirovac","city_id":"cGlyb3ZhY8WhaWJlbnNrby1rbmluc2thIMW-dXBhbmlqYWNyb2F0aWE"},"gain":30,"elevation":0,"block_added":936076,"block":968097,"address":"116w79GGtZCQ7FuECaGJh2m8Gbpu2utvRy7NydbBEq7xvAzbhBk"}}
```

**Comment by robputt** [comment]
So I am in the process of experimenting with exposing the miner's JSONRPC API locally within the Docker subnet, this will allow other containers to utilise it and interact with the miner in a more sane fashion rather than reading info in by parsing shell commands etc...

Within this API is this function https://github.com/helium/miner/blob/master/src/jsonrpc/miner_jsonrpc_info.erl#L33 which probably helps us here.

**Comment by shawaj** [comment]
@robputt nice idea 👍

Also, we could look at the peer book https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/basic-miner-operation/#checking-the-p2p-network

I think that's the definitive way to tell if it's relayed or not `miner peer book -s` and see if it has an ipv4 listen address rather than a p2p address. Maybe that can be done through the JSONRPC API too

https://github.com/helium/miner/blob/bca8473e15c6e0e639ef95bcc51438db9aa0092f/src/jsonrpc/miner_jsonrpc_peer.erl#L126

**Comment by MuratUrsavas** [comment]
I guess I have this problem with my MNTD. It is not relayed (approved by explorer and hotspotty app on demand tests) but the diagnostics report shows it relayed.
