### ISSUE TITLE
"waiting for miner"?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#58]
Does the "waiting for miner" show if the unit has not been asserted?

**Comment by shawaj** [comment]
https://discord.com/channels/404106811252408320/796070988118360094/852606571053056080

**Comment by ryanteck** [comment]
It shows that if it can't get the data from the miner in response to the request in #50 to instead of showing the raw data that it instead shows this more friendly message.

From some monitoring it seems that it can sometimes take 15 minutes from boot up for it to be in a state where it responds with data.

**Comment by shawaj** [comment]
Great, thanks @ryanteck will let them know  👍

**Comment by whittinghamj** [comment]
I have been looking at this issue for the past 48 hours. Multiple reboots does not fix the issue.

**Comment by shawaj** [comment]
@ryanteck think I found the issue. There seems to be a bug in the latest helium GA...

https://github.com/helium/miner/issues/816

We have several units facing this issue it seems. Which is why units like @whittinghamj has such as this one appear to be syncing in explorer but on diagnostics shows it is waiting for miner...

https://explorer.helium.com/hotspots/11KyE8XApNKMPztAgKJu2qYh2FmihsX686NqSTYxfJLxLzZw6kL

**Comment by shawaj** [comment]
Closing as this has been fixed by https://engineering.helium.com/2021/06/14/blockchain-release-bug-fixes-and-snapshot-update.html

https://github.com/helium/blockchain-core/pull/864
